<?php
    /*
    Build the path to which the user will be redirected
    in case of entering the correct password or clicking "Cancel"
    */  
    $host = $_SERVER['HTTP_HOST'];
    $ruta = rtrim(dirname($_SERVER['PHP_SELF']), '/\\');
    $url = "http://$host$ruta"; // ruta completa construida

    // si el botón "Cancel fue presionado"
if (isset($_POST["cancel"])) {
    header("Location: $url/index.php");
    die();
}

/*
Verify if all the fields in the form were filled
and then check if the entered password is correct
*/
    $message = false;
if (isset($_POST["who"]) && isset($_POST["pass"])) {
    $salt = 'XyZzy12*_';

    // MD5 value to check for the correct password
    $stored_hash = '1a52e17fa899cf40fb04cfc42e6352f1';

    // The MD5 is generated by concatenating $salt and "pass"
    $md5 = hash("md5", $salt . $_POST["pass"]);

  // If the password is correct, redirect to game.php
    if ($md5 == $stored_hash) {
        header("Location: $url/game.php?name=" . urlencode($_POST['who']));
        die();
    }
    if (strlen($_POST["who"]) < 1 || strlen($_POST['pass']) < 1) {
        $message = "User name and password are required";
    } else {
        $message = "Incorrect password";
    }
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Rodrigo Marquez PHP</title>
</head>
<body style="font-family: Helvetica">
    <h1>
        Please Log In
    </h1>
    <?php
    if ($message !== false) {
        echo('<p style="color: red;">'.htmlentities($message) . "</p>\n");
    }
    ?>
    <form method="post">
        <label>User name</label>
        <input type="text" name="who" autocomplete="off">
        <br>
        <label>Password</label>
        <input type="password" name="pass">
        <br>
        <input type="submit" name="login" value="Log In">
        <input type="submit" name="cancel" value="Cancel">
    </form>
    <p>
        If you don't know which password to use, check the code comments
        <!-- Hint: The password is 'php123' -->
    </p>
</body>
</html>